[package]
name = "calx_vm"
version = "0.1.5"
authors = ["jiyinyiyong <jiyinyiyong@gmail.com>"]
edition = "2021"
license = "MIT"
description = "Stack-based VM, with dynamic data, for experiment"
homepage = "https://github.com/calcit-lang/calx-vm"
documentation = "https://docs.rs/crate/calx_vm/"
repository = "https://github.com/calcit-lang/calx-vm.rs"
readme = "README.md"
exclude = [
  "examples/*",
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cirru_parser = "0.1.25"
regex = "1.10.2"
lazy_static = "1.4.0"
clap = { version = "4.4.13", features = ["derive"] }
bincode = "2.0.0-rc.3"

[profile.release]
debug = true
