[package]
name = "calx_vm"
version = "0.1.0"
authors = ["jiyinyiyong <jiyinyiyong@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cirru_parser = "0.1.1"
regex = "1"
lazy_static = "1.4.0"

[profile.release]
debug = true