on:
  release:
    types: [created]

name: Publish to crate

jobs:
  publish:
    name: Publish to cargo
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - run: cargo run -- -S examples/hello.cirru
      - run: cargo run -- -S examples/sum.cirru
      - run: cargo run -- -S examples/assert.cirru
      - run: cargo run -- -S examples/nested.cirru

      # - run: cargo test

      - uses: katyo/publish-crates@v1
        with:
          registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}
