on:
  release:
    types: [created]

name: Publish to crate

jobs:
  publish:
    name: Publish to cargo
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: nightly
          components: clippy

      - run: cargo run -- -s examples/hello.cirru
      - run: cargo run -- -s examples/sum.cirru
      - run: cargo run -- -s examples/assert.cirru
      - run: cargo run -- -s examples/nested.cirru
      - run: cargo run -- -s examples/named.cirru
      - run: cargo run -- examples/recur.cirru
      - run: cargo run -- --emit-binary target/a.calx examples/named.cirru && cargo run -- --eval-binary target/a.calx

      # - run: cargo test

      - uses: katyo/publish-crates@v1
        with:
          registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}
